global: 
  scrape_interval: 30s
scrape_configs: 
  - job_name: consumer
    scrape_interval: 30s
    metrics_path: /metrics
    scheme: http
    dns_sd_configs: 
      - names: [ 'consumer' ]
        type: A 
        port: 80